services:

  user-db:
    image: postgres
    container_name: users_db_postgres
    environment:
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_DB_USERNAME} -d ${USER_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5



  user-redis:
    image: redis:7-alpine
    container_name: user-service-redis
    ports:
      - "6379:6379"


  auth-db:
    image: postgres
    environment:
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    container_name: credentials_db_postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USERNAME} -d ${AUTH_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5



  order-db:
    image: postgres
    environment:
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    container_name: orders_db_postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ORDER_DB_USERNAME} -d ${ORDER_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5


  payment-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PAYMENT_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PAYMENT_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${PAYMENT_DB_NAME}
    container_name: payments-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181



  kafka-service:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



#  -------------------------------------------------------------------------------------------------------------

  discovery-server:
    image: lexavodoprovod/discovery-service:latest
    container_name: discovery-service-app
    ports:
      - "8761:8761"


  gateway-app:
    image: lexavodoprovod/api-gateway:latest
    container_name: api-gateway-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      discovery-server:
        condition: service_started



  user-app:
    image: lexavodoprovod/user-service:latest
    container_name: user-service-app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=${USER_DB_USERNAME}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      discovery-server:
        condition: service_started
      user-db:
        condition: service_healthy
      user-redis:
        condition: service_started



  auth-app:
    image: lexavodoprovod/auth-service:latest
    container_name: auth-service-app
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=${AUTH_DB_USERNAME}
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - DB_NAME=${AUTH_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}
      - REFRESH_TOKEN_EXPIRATION=${REFRESH_TOKEN_EXPIRATION}
    depends_on:
      discovery-server:
        condition: service_started
      auth-db:
        condition: service_healthy


  order-app:
    image: lexavodoprovod/order-service
    container_name: order-service-app
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=${ORDER_DB_USERNAME}
      - DB_PASSWORD=${ORDER_DB_PASSWORD}
      - DB_NAME=${ORDER_DB_NAME}
    depends_on:
      discovery-server:
        condition: service_started
      order-db:
        condition: service_healthy

  payment-service:
    image: lexavodoprovod/payment-service:latest
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=${PAYMENT_DB_USERNAME}
      - DB_PASSWORD=${PAYMENT_DB_PASSWORD}
      - DB_NAME=${PAYMENT_DB_NAME}
    depends_on:
      discovery-server:
        condition: service_started
      payment-db:
        condition: service_healthy