spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - AuthenticationFilter
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters:
                - AuthenticationFilter
  security:
    jwt:
      secret_key: ${SECRET_KEY}